/**
 * Static ship class definitions -- GENERATED, DO NOT EDIT BY HAND.
 *
 * Regenerate with:  node tools/extract-ship-classes.mjs --ts
 *
 * Every value is read verbatim from the original distribution's ship
 * configuration table, reference/ge-upstream/mbmgemp/GE/MSG/MBMGESHP.MSG,
 * which is the file the original game itself loaded at boot. No value here is
 * normalized, rounded or editorially adjusted; where a field looks unused for a
 * given class it is still canon's value, because the fields the game ignores
 * are decided by the code, not by the table.
 *
 * Classes whose TYPE is <NONE> are unused slots and are omitted: 10-20 and
 * 26-30. Slots 26-30 carry the stale leftover name "Cybertron Battle Cruiser"
 * and are NOT real classes. The active roster is 01-09, 21-25, 31-33 and 41.
 *
 * shipNameTemplate is canon's SNAME, a literal PREFIX. The original builds a
 * display name as sprintf("%s%u", SNAME, usrn*usrn + rnd%100) -- so "Cybertron "
 * becomes "Cybertron 223". Its trailing space is significant. USER classes have
 * an empty SNAME because players name their own ship.
 *
 * COLUMN MEANINGS (easy to transpose, and were, until 2026-09-01):
 *   noClaim               = canon NATK, the PREY's column -- how many combative
 *                           CPU ships may pursue this ship at once.
 *                           C: shipclass[victim].noclaim
 *   cybLowestClassAttacks = canon LATK, the HUNTER's column -- the lowest player
 *                           class this CPU pursues unprovoked.
 *                           C: shipclass[hunter].lowest_to_attk
 *   make                  = canon MAKE (tot_to_create). Read ONLY for CYBORG and
 *                           DROID classes; GEMAIN.C:2336-2338 skips USER classes,
 *                           so canon's 3 on player classes is inert.
 *
 * @see GEMAIN.C:835-875 -- the read loop that binds these fields by order
 * @see GEMAIN.C:2336-2358 -- the CYBORG/DROID-only spawn loop
 * @see reference/ge-upstream/PROVENANCE.md -- provenance and source precedence
 */

export interface ShipClassSeed {
  classNumber: number;
  typeName: string;
  shipNameTemplate: string;
  category: "PLAYER" | "CPU_COMBATIVE" | "CPU_DROID";
  maxShields: number;
  maxPhaser: number;
  hasTorpedo: boolean;
  hasMissile: boolean;
  hasDecoy: boolean;
  hasJammer: boolean;
  hasZipper: boolean;
  hasMine: boolean;
  canAttackPlanet: boolean;
  hasCloak: boolean;
  maxAcceleration: number;
  maxWarp: number;
  maxTons: number;
  maxPrice: bigint;
  scanRange: number;
  points: number;
  damageFactor: number;
  cybCanAttack: boolean;
  cybLowestClassAttacks: number;
  noClaim: number;
  make: number;
  tough: number;
}

export const SHIP_CLASSES: readonly ShipClassSeed[] = [

  // ─── Player ships (USER) ─────────────────────────────────────────
  {
    classNumber: 1,
    typeName: "Interceptor",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 10,
    maxPhaser: 10,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 5000,
    maxWarp: 10,
    maxTons: 1000,
    maxPrice: 65_000n,
    points: 750,
    scanRange: 100_000,
    cybCanAttack: true,
    noClaim: 1,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 90,
  },
  {
    classNumber: 2,
    typeName: "Stealth Fighter",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 5000,
    maxWarp: 20,
    maxTons: 2000,
    maxPrice: 500_000n,
    points: 1500,
    scanRange: 200_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 90,
  },
  {
    classNumber: 3,
    typeName: "Heavy Freighter",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 5,
    maxPhaser: 5,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 3000,
    maxWarp: 8,
    maxTons: 60_000,
    maxPrice: 40_000n,
    points: 500,
    scanRange: 50_000,
    cybCanAttack: false,
    noClaim: 0,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 200,
  },
  {
    classNumber: 4,
    typeName: "Destroyer",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 5000,
    maxWarp: 25,
    maxTons: 5000,
    maxPrice: 600_000n,
    points: 2000,
    scanRange: 100_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 90,
  },
  {
    classNumber: 5,
    typeName: "Star Cruiser",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 10_000,
    maxWarp: 25,
    maxTons: 3000,
    maxPrice: 700_000n,
    points: 5000,
    scanRange: 200_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 100,
  },
  {
    classNumber: 6,
    typeName: "Battle Cruiser",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 19,
    maxPhaser: 19,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 3000,
    maxWarp: 30,
    maxTons: 6000,
    maxPrice: 800_000n,
    points: 5000,
    scanRange: 250_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 125,
  },
  {
    classNumber: 7,
    typeName: "Frigate",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 12,
    maxPhaser: 12,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 10_000,
    maxWarp: 30,
    maxTons: 12_000,
    maxPrice: 1_250_000n,
    points: 5000,
    scanRange: 250_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 125,
  },
  {
    classNumber: 8,
    typeName: "Dreadnought",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 19,
    maxPhaser: 19,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 15_000,
    maxWarp: 50,
    maxTons: 40_000,
    maxPrice: 2_000_000n,
    points: 10_000,
    scanRange: 500_000,
    cybCanAttack: true,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 125,
  },
  {
    classNumber: 9,
    typeName: "Freight Barge",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 6,
    maxPhaser: 3,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 1000,
    maxWarp: 15,
    maxTons: 200_000,
    maxPrice: 3_000_000n,
    points: 5000,
    scanRange: 200_000,
    cybCanAttack: false,
    noClaim: 0,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 200,
  },

  // ─── Cybertron / Sarten combat ships (CYBORG) ────────────────────
  {
    classNumber: 21,
    typeName: "Cybertron Scout",
    shipNameTemplate: "Cybertron ",
    category: "CPU_COMBATIVE",
    maxShields: 2,
    maxPhaser: 2,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 2000,
    maxWarp: 8,
    maxTons: 900,
    maxPrice: 20_000n,
    points: 1000,
    scanRange: 50_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 10,
    tough: 0,
    damageFactor: 90,
  },
  {
    classNumber: 22,
    typeName: "Cybertron Battle Cruiser",
    shipNameTemplate: "Cyberquad ",
    category: "CPU_COMBATIVE",
    maxShields: 3,
    maxPhaser: 3,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 5000,
    maxWarp: 10,
    maxTons: 12_500,
    maxPrice: 20_000n,
    points: 2000,
    scanRange: 1000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 5,
    tough: 1,
    damageFactor: 100,
  },
  {
    classNumber: 23,
    typeName: "Cybertron Base Star",
    shipNameTemplate: "Cyber Base-",
    category: "CPU_COMBATIVE",
    maxShields: 9,
    maxPhaser: 16,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 0,
    maxWarp: 0,
    maxTons: 1_250_000,
    maxPrice: 20_000n,
    points: 10_000,
    scanRange: 200_000,
    cybCanAttack: false,
    noClaim: 0,
    cybLowestClassAttacks: 20,
    make: 1,
    tough: 1,
    damageFactor: 2000,
  },
  {
    classNumber: 24,
    typeName: "Sarten Attack Drone",
    shipNameTemplate: "SADx3",
    category: "CPU_COMBATIVE",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 1200,
    maxWarp: 8,
    maxTons: 100,
    maxPrice: 20_000n,
    points: 50,
    scanRange: 20_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 6,
    tough: 0,
    damageFactor: 30,
  },
  {
    classNumber: 25,
    typeName: "Sarten Obliterator",
    shipNameTemplate: "SOBx9",
    category: "CPU_COMBATIVE",
    maxShields: 5,
    maxPhaser: 16,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: false,
    hasJammer: false,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 200,
    maxWarp: 15,
    maxTons: 234_000,
    maxPrice: 20_000n,
    points: 500,
    scanRange: 400_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 3,
    make: 2,
    tough: 1,
    damageFactor: 500,
  },

  // ─── Droids (DROID) ──────────────────────────────────────────────
  {
    classNumber: 31,
    typeName: "Lydorian Garbage Scow",
    shipNameTemplate: "NCC Lx4",
    category: "CPU_DROID",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 50,
    maxWarp: 1,
    maxTons: 10_000,
    maxPrice: 20_000n,
    points: 5,
    scanRange: 25_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 2,
    tough: 0,
    damageFactor: 100,
  },
  {
    classNumber: 32,
    typeName: "Murdonian Transport",
    shipNameTemplate: "Trans-Gal #2",
    category: "CPU_DROID",
    maxShields: 2,
    maxPhaser: 5,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 400,
    maxWarp: 8,
    maxTons: 30_000,
    maxPrice: 20_000n,
    points: 200,
    scanRange: 25_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 2,
    tough: 0,
    damageFactor: 100,
  },
  {
    classNumber: 33,
    typeName: "Vakory Survey Drone",
    shipNameTemplate: "Vakory SD-82",
    category: "CPU_DROID",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 1200,
    maxWarp: 4,
    maxTons: 100,
    maxPrice: 20_000n,
    points: 50,
    scanRange: 25_000,
    cybCanAttack: false,
    noClaim: 2,
    cybLowestClassAttacks: 0,
    make: 2,
    tough: 0,
    damageFactor: 100,
  },

  // ─── Player ships (USER) ─────────────────────────────────────────
  {
    classNumber: 41,
    typeName: "Sysopian Death Star",
    shipNameTemplate: "",
    category: "PLAYER",
    maxShields: 6,
    maxPhaser: 5,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 5000,
    maxWarp: 255,
    maxTons: 100_000_000,
    maxPrice: 32_000_000n,
    points: 1000,
    scanRange: 1_000_000,
    cybCanAttack: true,
    noClaim: 0,
    cybLowestClassAttacks: 0,
    make: 3,
    tough: 0,
    damageFactor: 100,
  },
] as const;
