/**
 * Static ship class definitions.
 * Sources: reference/wiki/player-ships.md (classes 1,2,3,4,5,6,7,8,9,34)
 *          reference/wiki/cpu-ships.md    (classes 21,22,23,24,25,31,32,33)
 *
 * Normalization rules:
 *   - "5k" / "1m" / "1.25m" → integer (e.g. 5000, 1_000_000, 1_250_000)
 *   - Y/N → boolean
 *   - "###" in shipNameTemplate preserved literally (runtime fill-in suffix)
 *   - Player ships: make=0, tough=0, noClaim=0
 *   - CPU ships: maxPrice=0n; player columns cybCanAttack/cybLowestClassAttacks set to false/0
 */

export interface ShipClassSeed {
  classNumber: number;
  typeName: string;
  shipNameTemplate: string;
  category: "PLAYER" | "CPU_COMBATIVE" | "CPU_DROID";
  maxShields: number;
  maxPhaser: number;
  hasTorpedo: boolean;
  hasMissile: boolean;
  hasDecoy: boolean;
  hasJammer: boolean;
  hasZipper: boolean;
  hasMine: boolean;
  canAttackPlanet: boolean;
  hasCloak: boolean;
  maxAcceleration: number;
  maxWarp: number;
  maxTons: number;
  maxPrice: bigint;
  scanRange: number;
  points: number;
  damageFactor: number;
  cybCanAttack: boolean;
  cybLowestClassAttacks: number;
  noClaim: number;
  make: number;
  tough: number;
}

export const SHIP_CLASSES: readonly ShipClassSeed[] = [
  // ─── Player Ships (reference/wiki/player-ships.md) ────────────────────────
  {
    classNumber: 1,
    typeName: "Interceptor",
    shipNameTemplate: "Interceptor",
    category: "PLAYER",
    maxShields: 10,
    maxPhaser: 10,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 5_000,
    maxWarp: 10,
    maxTons: 1_000,
    maxPrice: 65_000n,
    scanRange: 20_000,
    points: 750,
    damageFactor: 90,
    cybCanAttack: true,
    cybLowestClassAttacks: 1,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 2,
    typeName: "Stealth Fighter",
    shipNameTemplate: "Stealth Fighter",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 5_000,
    maxWarp: 20,
    maxTons: 2_000,
    maxPrice: 500_000n,
    scanRange: 25_000,
    points: 1_500,
    damageFactor: 90,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 3,
    typeName: "Heavy Freighter",
    shipNameTemplate: "Heavy Freighter",
    category: "PLAYER",
    maxShields: 5,
    maxPhaser: 5,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 3_000,
    maxWarp: 8,
    maxTons: 60_000,
    maxPrice: 40_000n,
    scanRange: 12_000,
    points: 500,
    damageFactor: 200,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 4,
    typeName: "Destroyer",
    shipNameTemplate: "Destroyer",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 5_000,
    maxWarp: 25,
    maxTons: 5_000,
    maxPrice: 600_000n,
    scanRange: 28_000,
    points: 2_000,
    damageFactor: 90,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 5,
    typeName: "Star Cruiser",
    shipNameTemplate: "Star Cruiser",
    category: "PLAYER",
    maxShields: 15,
    maxPhaser: 15,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 10_000,
    maxWarp: 25,
    maxTons: 3_000,
    maxPrice: 700_000n,
    scanRange: 30_000,
    points: 5_000,
    damageFactor: 100,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 6,
    typeName: "Battle Cruiser",
    shipNameTemplate: "Battle Cruiser",
    category: "PLAYER",
    maxShields: 19,
    maxPhaser: 19,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 3_000,
    maxWarp: 30,
    maxTons: 6_000,
    maxPrice: 800_000n,
    scanRange: 50_000,
    points: 5_000,
    damageFactor: 125,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 7,
    typeName: "Frigate",
    shipNameTemplate: "Frigate",
    category: "PLAYER",
    maxShields: 12,
    maxPhaser: 12,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 10_000,
    maxWarp: 30,
    maxTons: 12_000,
    maxPrice: 1_250_000n,
    scanRange: 40_000,
    points: 5_000,
    damageFactor: 125,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 8,
    typeName: "Dreadnought",
    shipNameTemplate: "Dreadnought",
    category: "PLAYER",
    maxShields: 19,
    maxPhaser: 19,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 15_000,
    maxWarp: 50,
    maxTons: 40_000,
    maxPrice: 2_000_000n,
    scanRange: 75_000,
    points: 10_000,
    damageFactor: 125,
    cybCanAttack: true,
    cybLowestClassAttacks: 2,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 9,
    typeName: "Freight Barge",
    shipNameTemplate: "Freight Barge",
    category: "PLAYER",
    maxShields: 6,
    maxPhaser: 3,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 1_000,
    maxWarp: 15,
    maxTons: 200_000,
    maxPrice: 3_000_000n,
    scanRange: 18_000,
    points: 5_000,
    damageFactor: 200,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 0,
    tough: 0,
  },
  {
    classNumber: 34,
    typeName: "Sysopian Death Star",
    shipNameTemplate: "Sysopian Death Star",
    category: "PLAYER",
    maxShields: 6,
    maxPhaser: 5,
    hasTorpedo: true,
    hasMissile: true,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: true,
    maxAcceleration: 5_000,
    maxWarp: 255,
    maxTons: 100_000_000,
    maxPrice: 32_000_000n,
    scanRange: 120_000,
    points: 1_000,
    damageFactor: 100,
    cybCanAttack: true,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 0,
    tough: 0,
  },

  // ─── CPU Combative Ships (reference/wiki/cpu-ships.md) ───────────────────
  {
    classNumber: 21,
    typeName: "Cybertron Scout",
    shipNameTemplate: "Cybertron ###",
    category: "CPU_COMBATIVE",
    maxShields: 2,
    maxPhaser: 2,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 2_000,
    maxWarp: 8,
    maxTons: 900,
    maxPrice: 0n,
    scanRange: 25_000,
    points: 1_000,
    damageFactor: 90,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 10,
    tough: 0,
  },
  {
    classNumber: 22,
    typeName: "Cybertron Battle Cruiser",
    shipNameTemplate: "Cyberquad ###",
    category: "CPU_COMBATIVE",
    maxShields: 3,
    maxPhaser: 3,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: true,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 5_000,
    maxWarp: 10,
    maxTons: 12_500,
    maxPrice: 0n,
    scanRange: 45_000,
    points: 2_000,
    damageFactor: 100,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 5,
    tough: 1,
  },
  {
    classNumber: 23,
    typeName: "Cybertron Base Star",
    shipNameTemplate: "Cyber Base-###",
    category: "CPU_COMBATIVE",
    maxShields: 9,
    maxPhaser: 16,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 0,
    maxWarp: 0,
    maxTons: 1_250_000,
    maxPrice: 0n,
    scanRange: 60_000,
    points: 10_000,
    damageFactor: 2_000,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 20,
    make: 1,
    tough: 1,
  },
  {
    classNumber: 24,
    typeName: "Sarten Attack Drone",
    shipNameTemplate: "SADx3###",
    category: "CPU_COMBATIVE",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 1_200,
    maxWarp: 8,
    maxTons: 100,
    maxPrice: 0n,
    scanRange: 20_000,
    points: 50,
    damageFactor: 30,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 6,
    tough: 0,
  },
  {
    classNumber: 25,
    typeName: "Sarten Obliterator",
    shipNameTemplate: "SOBx9###",
    category: "CPU_COMBATIVE",
    maxShields: 5,
    maxPhaser: 16,
    hasTorpedo: true,
    hasMissile: false,
    hasDecoy: false,
    hasJammer: false,
    hasZipper: false,
    hasMine: false,
    canAttackPlanet: true,
    hasCloak: false,
    maxAcceleration: 200,
    maxWarp: 15,
    maxTons: 234_000,
    maxPrice: 0n,
    scanRange: 55_000,
    points: 500,
    damageFactor: 500,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 3,
    make: 2,
    tough: 1,
  },

  // ─── CPU Droid Ships (reference/wiki/cpu-ships.md) ────────────────────────
  {
    classNumber: 31,
    typeName: "Lydorian Garbage Scow",
    shipNameTemplate: "NCC Lx4###",
    category: "CPU_DROID",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 50,
    maxWarp: 1,
    maxTons: 10_000,
    maxPrice: 20_000n,
    scanRange: 12_000,
    points: 5,
    damageFactor: 100,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 2,
    tough: 0,
  },
  {
    classNumber: 32,
    typeName: "Murdonian Transport",
    shipNameTemplate: "Trans-Gal #2###",
    category: "CPU_DROID",
    maxShields: 2,
    maxPhaser: 5,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 400,
    maxWarp: 8,
    maxTons: 30_000,
    maxPrice: 20_000n,
    scanRange: 30_000,
    points: 200,
    damageFactor: 100,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 2,
    tough: 0,
  },
  {
    classNumber: 33,
    typeName: "Vakory Survey Drone",
    shipNameTemplate: "Vakory SD-82###",
    category: "CPU_DROID",
    maxShields: 1,
    maxPhaser: 1,
    hasTorpedo: false,
    hasMissile: false,
    hasDecoy: true,
    hasJammer: true,
    hasZipper: true,
    hasMine: true,
    canAttackPlanet: false,
    hasCloak: false,
    maxAcceleration: 1_200,
    maxWarp: 4,
    maxTons: 100,
    maxPrice: 25_000n,
    // @see reference/wiki/cpu-ships.md Vakory Survey Drone row — Scan column = 25000
    scanRange: 25_000,
    points: 50,
    damageFactor: 100,
    cybCanAttack: false,
    cybLowestClassAttacks: 0,
    noClaim: 0,
    make: 2,
    tough: 0,
  },
] as const;
