/**
 * Wire types for backend GameGateway ↔ React frontend communication.
 *
 * This file is a copy of specs/003-ship-commands/contracts/shared-types.ts.
 * Do NOT edit this file directly — edit the canonical contract and sync.
 * Structural parity is enforced by frontend/test/contracts-parity.spec.ts.
 */

/**
 * Shared wire types between backend GameGateway and the React frontend.
 *
 * This file is the canonical contract. The frontend duplicates these declarations into
 * `frontend/src/types/contracts.ts`; both copies must remain identical. A TS-level
 * structural check in `frontend/test/contracts-parity.spec.ts` (added under feature 003)
 * fails the frontend test suite if the two diverge.
 *
 * @see specs/003-ship-commands/contracts/websocket-events.md
 */

export type EventLogCategory = 'system' | 'info' | 'success' | 'combat';

export interface EventLogLine {
  text: string;
  category: EventLogCategory;
}

/**
 * Object class for a `scanGrid` cell.
 *
 * `'self'` is the connecting player's own ship at the geometric centre of the
 * range-scan map (`map[MAXY/2][MAXX/2] = '*'` per `GECMDS.C:2721`). The
 * backend includes the self-cell so the wire payload is self-describing — the
 * frontend renders it like any other cell, no client-side overlay logic.
 *
 * @see specs/003-ship-commands/spec.md `Clarifications` 2026-05-02 Q2
 */
export type ScanCellType = 'ship' | 'planet' | 'wormhole' | 'self';

/**
 * Range-scan grid dimensions, taken verbatim from the original game.
 *
 * Source: `reference/ge-source/GEMAIN.H` lines 121-122 — `#define MAXX 30`,
 * `#define MAXY 15`. The `scan_lo` renderer at `GECMDS.C:2640-2726` declares
 * `map[MAXY][MAXX]` and centres the player at `map[MAXY/2][MAXX/2]`.
 *
 * The frontend MUST read these constants from this module rather than
 * hard-coding 30/15 — if the original ever needed to be revisited, this file
 * is the single source of truth and the backend ship-coord-to-cell projection
 * and the frontend grid render must move together.
 *
 * @see GEMAIN.H:121
 * @see GEMAIN.H:122
 * @see GECMDS.C:2681 (xfactor / yfactor projection)
 * @see GECMDS.C:2721 (player-centre placement)
 */
export const SCAN_GRID_WIDTH = 30 as const;
export const SCAN_GRID_HEIGHT = 15 as const;

export interface ScanCell {
  /** integer 0..SCAN_GRID_WIDTH-1, range-scan column */
  x: number;
  /** integer 0..SCAN_GRID_HEIGHT-1, range-scan row */
  y: number;
  type: ScanCellType;
  /**
   * The original game's single-ASCII character for this object.
   * `'self'` cells carry `'*'` per `GECMDS.C:2721`. See data-model.md.
   */
  char: string;
}

/** Inbound: client → server `command` */
export interface CommandRequest {
  input: string;
}

/** Outbound: server → client `command:result` */
export interface CommandResultPayload {
  lines: EventLogLine[];
  /** present only when the command was `scan` (or an alias) */
  scanGrid?: ScanCell[];
}
