/**
 * Canonical neutral-zone (sector 0,0) planet fixture.
 *
 * GENERATED by tools/extract-s00.mjs from the shipped sysop option database.
 *
 * Contains material Copyright (C) 1988-1992 Michael B. Murdock, from Galactic
 * Empire release 3.2e, released by its author under GPL-2.0-or-later. This
 * port is AGPL-3.0-or-later; see NOTICE at the repository root.
 * DO NOT EDIT BY HAND — regenerate, and let
 * test/balance/s00-canon.balance.spec.ts re-check it against the original.
 *
 * GEMAIN.C:909-930 reads S00PLNUM entries of eight options each; GEPLANET.C:
 * 497-527 dispatches each on its type to build a hub, a bare planet, or a
 * wormhole portal.
 *
 * @see reference/ge-upstream/mbmgemp/GE/REL/MBMGEMSG.MSG — the S00P* blocks
 * @see GEMAIN.C:476 S00PLNUM
 * @see GEMAIN.C:909-930 the read loop
 * @see GEPLANET.C:497-528 type dispatch
 */

import { S00Entry } from './galaxy.types';
import { NEUTRAL_ZONE_OWNER } from '../combat/neutral-zone';

/**
 * Number of planets in the neutral-zone fixture.
 * Shipped S00PLNUM, clamped by GEMAIN.C:476 to 3..9.
 */
export const S00_PLNUM = 6 as const;

/**
 * Frozen array of neutral-zone entries for sector (0,0). Index i is plnum i+1.
 *
 * Coordinates are the shipped integer options divided by 10000 (GEMAIN.C:
 * 922-925), giving an offset within the origin sector cell.
 *
 * env and res are QUALITY GRADES, both read through the same four messages —
 * 0 = Poor, 1 = Marginal, 2 = Good, 3 = Very Good
 * (GECMDS.C:2337-2348 prints SCAN12..SCAN15 for env, then again for res;
 * MBMGEMSG.MSG:3570-3585). Higher is better, which GEPLANET.C:280 confirms:
 * production scales with `(enviorn + resource + 2) * .25`.
 *
 * The shipped owner is `*EMPIRE*` on every entry; this port substitutes
 * NEUTRAL_ZONE_OWNER, a sentinel that cannot collide with a player id.
 * @see src/game/combat/neutral-zone.ts
 */
export const S00: S00Entry[] = Object.freeze([
  {
    // plnum=1 — Zygor, build_plan_1 — weapons hub (GEPLANET.C:503-506)
    type: 1,
    name: "Zygor",
    xcoord: 0.5,
    ycoord: 0.5,
    env: 3,   // Very Good
    res: 3,   // Very Good
    owner: NEUTRAL_ZONE_OWNER,
  },
  {
    // plnum=2 — Tahanian Station, build_plan_2 — troops/men/food hub (GEPLANET.C:510-513)
    type: 2,
    name: "Tahanian Station",
    xcoord: 0.7,
    ycoord: 0.7,
    env: 3,   // Very Good
    res: 3,   // Very Good
    owner: NEUTRAL_ZONE_OWNER,
  },
  {
    // plnum=3 — Enforcer Planet, build_other — bare planet (GEPLANET.C:526)
    type: 0,
    name: "Enforcer Planet",
    xcoord: 0.2,
    ycoord: 0.2,
    env: 1,   // Marginal
    res: 0,   // Poor
    owner: NEUTRAL_ZONE_OWNER,
  },
  {
    // plnum=4 — Kayriez Portal, build_worm — wormhole portal (GEPLANET.C:517-520)
    type: 3,
    name: "Kayriez Portal",
    xcoord: 0.11,
    ycoord: 0.67,
    env: 0,   // Poor
    res: 0,   // Poor
    owner: NEUTRAL_ZONE_OWNER,
  },
  {
    // plnum=5 — Lydorian Portal, build_worm — wormhole portal (GEPLANET.C:517-520)
    type: 3,
    name: "Lydorian Portal",
    xcoord: 0.67,
    ycoord: 0.15,
    env: 0,   // Poor
    res: 0,   // Poor
    owner: NEUTRAL_ZONE_OWNER,
  },
  {
    // plnum=6 — Tryklon Portal, build_worm — wormhole portal (GEPLANET.C:517-520)
    type: 3,
    name: "Tryklon Portal",
    xcoord: 0.55,
    ycoord: 0.78,
    env: 0,   // Poor
    res: 0,   // Poor
    owner: NEUTRAL_ZONE_OWNER,
  },
]) as S00Entry[];
