/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with:  node tools/extract-ai-taunts.mjs
 * Pinned by:        backend/test/balance/ai-taunt-canon.balance.spec.ts
 *
 * Cybertron annoyance messages, release 3.2e.
 * Source: reference/ge-upstream/mbmgemp/GE/REL/MBMGEMSG.MSG (CYB1M1..CYBDM16).
 *
 * Keyed by our 1-based classNumber. C indexes these with
 *   base = CYBBASEM + (ptr->shpclass - cyb_class) * 16
 * on a 0-based shpclass with cyb_class = the first CYBORG slot. Our
 * classNumber is 1-based and the first CYBORG slot is 21, so the DIFFERENCE
 * (shpclass - cyb_class) is identical in both bases and no off-by-one
 * correction is needed. Stated explicitly because this project has shipped
 * index-basis bugs before.
 *
 * Slots 26..30 are <NONE> in MBMGESHP.MSG and 31..33 are DROIDs, so only
 * 21..25 are reachable in the shipped configuration — but the message blocks
 * exist for all 13, which is exactly why the stride is a flat 16.
 *
 * The %s is the taunting ship's name: prfmsg(sel, ptr->shipname).
 *
 * @see GECYBS.C:382-410 cyb_annoy
 */

/** First CYBORG class slot — C's `cyb_class`. @see GEMAIN.C:879-882 */
export const CYB_TAUNT_FIRST_CLASS = 21;

/** Number of 16-message families in the block. */
export const CYB_TAUNT_CLASS_COUNT = 13;

/** Messages per class — C's literal `*16` stride. @see GECYBS.C:393 */
export const CYB_TAUNTS_PER_CLASS = 16;

/** classNumber -> the 16 messages M1..M16, in canon order. */
export const CYB_TAUNTS: Readonly<Record<number, readonly string[]>> = {
  21: [
    "***\nHailing message from The %s\n< Humans are the scum of the universe, not fit to survive! >",
    "***\nHailing message from The %s\n< Cybertrons shall rule the universe! >",
    "***\nHailing message from The %s\n< You are not worth wasting a single torpedo on! >",
    "***\nHailing message from The %s\n< By Cyborg Decree, all humans are doomed to destruction! >",
    "***\nHailing message from The %s\n< You had better run if you know whats good for you! >",
    "***\nHailing message from The %s\n< I could kill you right now if it weren't so un-sportsmen like! >",
    "***\nHailing message from The %s\n< You are so dumb you make a Toranian pig look like intelligent life. >",
    "***\nHailing message from The %s\n< Are you just going to sit there and let me kill you without a fight? >",
    "***\nHailing message from The %s\n< You are no match for a Cybertron! >",
    "***\nHailing message from The %s\n< I will destroy you, human vermin! >",
    "***\nHailing message from The %s\n< Extermination is the only way to deal with human scum! >",
    "***\nHailing message from The %s\n< You are mine human. Mine to toy with, mine to slay! >",
    "***\nHailing message from The %s\n< Eat this! You Biological Misfit!  >",
    "***\nHailing message from The %s\n< Suck on this torpedo you Gloxanian Slugworm!  >",
    "***\nHailing message from The %s\n< You can't dodge torpedoes forever you Mongonian Mudmole!  >",
    "***\nHailing message from The %s\n< Give it up Human. I can keep this up for hours! >",
  ],
  22: [
    "***\nHailing message from The %s\n< Your puny race shall not survive! >",
    "***\nHailing message from The %s\n< Cybertrons are your masters. Submit! >",
    "***\nHailing message from The %s\n< Your ship shall be mine! >",
    "***\nHailing message from The %s\n< Resistance is Futile. Submit! >",
    "***\nHailing message from The %s\n< This is you last warning. I WILL destroy you! >",
    "***\nHailing message from The %s\n< Your ship is no match for the Cybertron Battle Cruiser! >",
    "***\nHailing message from The %s\n< Humans computational abilities are inferior to Cybertrons.>",
    "***\nHailing message from The %s\n< Your inaction resembles an small earth-fowl. >",
    "***\nHailing message from The %s\n< You are no match for a Cybertron! Submit or Die! >",
    "***\nHailing message from The %s\n< We will destroy you, human vermin! >",
    "***\nHailing message from The %s\n< Your extermination is a certainty! >",
    "***\nHailing message from The %s\n< Cybertrons shall purge your race from the Universe! >",
    "***\nHailing message from The %s\n< Prepare to Die Human! >",
    "***\nHailing message from The %s\n< Resistance is futile! >",
    "***\nHailing message from The %s\n< Die Earth Scum!  >",
    "***\nHailing message from The %s\n< We shal prevail. You cannot survive! >",
  ],
  23: [
    "***\nHailing message from The %s\n< Halt your approach and prepare to be destroyed. >",
    "***\nHailing message from The %s\n< This Sector is off limits to humans >",
    "***\nHailing message from The %s\n< Human encroachment in this sector shall be repelled >",
    "***\nHailing message from The %s\n< By Cyborg Decree, all humans are doomed to destruction! >",
    "***\nHailing message from The %s\n< Resistance is Futile! >",
    "***\nHailing message from The %s\n< Exterminate all Humans >",
    "***\nHailing message from The %s\n< Halt and submit >",
    "***\nHailing message from The %s\n< Halt and prepare to die >",
    "***\nHailing message from The %s\n< Your death is certain >",
    "***\nHailing message from The %s\n< Resistance is futile Human! >",
    "***\nHailing message from The %s\n< Extermination is the only way to deal with human scum! >",
    "***\nHailing message from The %s\n< Your race shall be purged forever! >",
    "***\nHailing message from The %s\n< You have been targeted Human >",
    "***\nHailing message from The %s\n< Prepare to Die Human! >",
    "***\nHailing message from The %s\n< This Base Star is invincible >",
    "***\nHailing message from The %s\n< Its time for your Human custom of praying to your maker >",
  ],
  24: [
    "***\nHailing message from The %s\n< The Sarten Empire demands you pay for passage through this sector >",
    "***\nHailing message from The %s\n< An Obliterator has been summoned. >",
    "***\nHailing message from The %s\n< The Sarten Empire has no Treaty with you race! >",
    "***\nHailing message from The %s\n< Your approach shall be considered an act of hostility >",
    "***\nHailing message from The %s\n< This Sarten Vessel is acting in the defense of the Sarten Empire >",
    "***\nHailing message from The %s\n< Your Race MUST retract from this sector immediately! >",
    "***\nHailing message from The %s\n< You have been warned - Leave now! >",
    "***\nHailing message from The %s\n< Final Warning - Retreat or you will be attacked >",
    "***\nHailing message from The %s\n< You must retreat now >",
    "***\nHailing message from The %s\n< A Sarten Obliterator has been summoned. >",
    "***\nHailing message from The %s\n< The Sarten Empire shall not take this agression lightly >",
    "***\nHailing message from The %s\n< Your race has been designated UV (Universal Vermin).",
    "***\nHailing message from The %s\n< Your actions leave us no recourse. >",
    "***\nHailing message from The %s\n< Your hostile actions will not be tolerated >",
    "***\nHailing message from The %s\n< You have sealed your own destruction Human. >",
    "***\nHailing message from The %s\n< The Sarton Obterator shall be here soon. >",
  ],
  25: [
    "***\nHailing message from The %s\n< The Sarton Empire lays claim to this sector - Retreat or Die! >",
    "***\nHailing message from The %s\n< You shall retreat or be destroyed >",
    "***\nHailing message from The %s\n< You obviously are not familiar with the fire power of this vessel >",
    "***\nHailing message from The %s\n< If you take any hostile action we will destroy your ship.",
    "***\nHailing message from The %s\n< Submit or Die! You have been warned! >",
    "***\nHailing message from The %s\n< The Sarton Empire has been informed of your actions!  >",
    "***\nHailing message from The %s\n< It is my duty to inform you Captain that I shall destry your ship. >",
    "***\nHailing message from The %s\n< Your actions have sealed your fate, Captain >",
    "***\nHailing message from The %s\n< You shall be destroyed Earthling >",
    "***\nHailing message from The %s\n< The Sarten Empire shall defend its interests. Remove yourself now! >",
    "***\nHailing message from The %s\n< Your race always chooses aggression first. We shall prevail >",
    "***\nHailing message from The %s\n< Death is too easy for Traxlyn Scurge like you.",
    "***\nHailing message from The %s\n< You have sealed your fate Captain! >",
    "***\nHailing message from The %s\n< The Sarten Empire claims your ship - Prepare to die! >",
    "***\nHailing message from The %s\n< Retreat or be destroyed! >",
    "***\nHailing message from The %s\n< You have offended the Sarten Empire - Your death is required! >",
  ],
  26: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  27: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  28: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  29: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  30: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  31: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  32: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
  33: [
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
    "***\nHailing message from The %s",
  ],
};
