#!/usr/bin/env node
/**
 * Extract canon's in-game help from MBMGEHLP.MSG into a TypeScript module.
 *
 * Canon ships 61 help entries and 45 of them document exactly ONE command
 * (HLPTOR, HLPPHA, HLPMIN, HLPLOC ...). That is why MINFMT tells a player
 * "Type HELP MINE for the correct usage". The port had 8 thematic topics, so a
 * pilot following the game's own instruction hit "Unknown help topic".
 *
 * Hand-transcription is what produced the scanRange drift and, in this very
 * file, the Mark-19 shield price that HLPNEW2 gets wrong. So the text is
 * GENERATED, and test/balance/help-canon.balance.spec.ts re-reads the original
 * to prove it has not drifted.
 *
 * Usage:  node tools/extract-help.mjs --ts > backend/src/game/commands/help/canon-help.generated.ts
 *
 * @see reference/ge-upstream/mbmgemp/GE/REL/MBMGEHLP.MSG
 * @see GECMDS.C cmd_help
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
export const HELP_MSG_PATH = join(here, '..', 'reference', 'ge-upstream', 'mbmgemp', 'GE', 'REL', 'MBMGEHLP.MSG');

/** Strip ANSI SGR sequences and the [2J screen clear canon opens each page with. */
function stripAnsi(s) {
  return s.replace(/\x1b?\[[0-9;]*[A-Za-z]/g, '');
}

export function extractHelp(rawIn = readFileSync(HELP_MSG_PATH, 'latin1')) {
  // Strip ANSI FIRST. Canon closes most pages with `ESC[0m} T`, the reset
  // sitting on the same line before the brace — so matching on a line-initial
  // '}' found only 22 of the 61 entries and silently merged the other 39 into
  // their neighbours. Colour has to come off before the structure is legible.
  const raw = stripAnsi(rawIn);
  const out = new Map();
  // Entries look like:  HLPTOR {....multi-line....\n} T
  // Terminators are usually ' } T ' — INDENTED. Anchoring on '^}' found only
  // 22 of the 61 entries and silently swallowed the rest into their neighbours.
  const re = /^(HLP[A-Z0-9]*)\s*\{([\s\S]*?)^[ \t]*\}[ \t]*T/gm;
  let m;
  while ((m = re.exec(raw)) !== null) {
    const id = m[1];
    const body = m[2]
      .split(/\r?\n/)
      // Canon pads pages with trailing blanks; keep interior blanks only.
      .map((l) => l.replace(/\s+$/, ''));
    while (body.length && body[0] === '') body.shift();
    while (body.length && body[body.length - 1] === '') body.pop();
    out.set(id, body);
  }
  return out;
}

if (process.argv.includes('--ts')) {
  const help = extractHelp();
  const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  console.log(`/**
 * GENERATED by tools/extract-help.mjs — do not edit by hand.
 *
 * Canon's in-game help, verbatim from GE/REL/MBMGEHLP.MSG (release 3.2e), with
 * ANSI colour and the [2J page-clear stripped.
 *
 * ${help.size} entries. Canon's help states design INTENT and is not
 * authoritative for a number — MBMGEMSG.MSG is. HLPNEW2 quotes a Mark-19
 * shield at 250.0m where SHLDPR19 says 200000000, which is exactly why the
 * price tables in help-topics.ts are computed from the option data instead of
 * taken from here.
 *
 * @see tools/extract-help.mjs
 * @see test/balance/help-canon.balance.spec.ts — re-reads the original
 */
export const CANON_HELP: Readonly<Record<string, ReadonlyArray<string>>> = Object.freeze({`);
  for (const [id, lines] of help) {
    console.log(`  ${id}: Object.freeze([`);
    for (const l of lines) console.log(`    '${esc(l)}',`);
    console.log('  ]),');
  }
  console.log('});');
}
