#!/usr/bin/env node
/**
 * Extract the neutral-zone (sector 0,0) planet table from MBMGEMSG.MSG.
 *
 * GEMAIN.C:909-930 reads `s00plnum` entries out of the sysop option database,
 * eight options per entry (`#define NPL 8`, GEMAIN.C:905), always in this
 * order: DEF, NM, OWN, TYP, X, Y, ENV, RES. The X/Y options are integers in
 * 100..9900 and the C divides them by 10000.0 to get a within-sector offset
 * (GEMAIN.C:922-925).
 *
 * GEPLANET.C:497-528 dispatches on the type: 1 -> build_plan_1 (weapons hub),
 * 2 -> build_plan_2 (troops/men/food hub), 3 -> build_worm (wormhole portal),
 * anything else -> build_other (bare planet).
 *
 * This exists because the fixture it replaces was hand-transcribed, and was
 * wrong in every field: five invented planets instead of six shipped ones, no
 * wormhole portals, and an inverted environment legend.
 *
 * Usage: node tools/extract-s00.mjs [--json | --ts]
 *
 * @see reference/ge-upstream/PROVENANCE.md
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(HERE, '../reference/ge-upstream/mbmgemp/GE/REL/MBMGEMSG.MSG')

const text = readFileSync(SRC, 'utf8')

/** Value inside an option's braces, after the trailing `: ` or `? `. */
function opt(id) {
  const m = new RegExp(`^${id} \\{([^}]*)\\}`, 'm').exec(text)
  if (!m) throw new Error(`option ${id} not found in ${SRC}`)
  const inner = m[1]
  const c = inner.lastIndexOf(': ')
  const q = inner.lastIndexOf('? ')
  if (q > c) return inner.slice(q + 2).trim()
  if (c !== -1) return inner.slice(c + 2).trim()
  return inner.trim()
}

/** GEMAIN.C:476 -- s00plnum = numopt(S00PLNUM,3,9). */
const plnum = Math.min(9, Math.max(3, Number(opt('S00PLNUM'))))

const entries = []
for (let n = 1; n <= plnum; ++n) {
  // GEMAIN.C:913-915 -- ynopt(classbase); a NO here is a fatal table error.
  if (opt(`S00P${n}DEF`) !== 'YES')
    throw new Error(`S00P${n}DEF is not YES but S00PLNUM is ${plnum}`)
  entries.push({
    plnum: n,
    name: opt(`S00P${n}NM`),
    owner: opt(`S00P${n}OWN`),
    type: Number(opt(`S00P${n}TYP`)),
    xcoord: Number(opt(`S00P${n}X`)) / 10000,
    ycoord: Number(opt(`S00P${n}Y`)) / 10000,
    env: Number(opt(`S00P${n}ENV`)),
    res: Number(opt(`S00P${n}RES`)),
  })
}

const mode = process.argv[2] ?? '--json'

if (mode === '--json') {
  console.log(JSON.stringify({ S00PLNUM: plnum, entries }, null, 2))
  process.exit(0)
}

if (mode !== '--ts') {
  console.error('usage: node tools/extract-s00.mjs [--json | --ts]')
  process.exit(2)
}

/** GEPLANET.C:497-528 build dispatch, for the generated comment. */
const BUILD = {
  1: 'build_plan_1 — weapons hub (GEPLANET.C:503-506)',
  2: 'build_plan_2 — troops/men/food hub (GEPLANET.C:510-513)',
  3: 'build_worm — wormhole portal (GEPLANET.C:517-520)',
}
/** GECMDS.C:2337-2348 maps env AND res through SCAN12..SCAN15. */
const GRADE = ['Poor', 'Marginal', 'Good', 'Very Good']

const lines = []
lines.push(`/**
 * Canonical neutral-zone (sector 0,0) planet fixture.
 *
 * GENERATED by tools/extract-s00.mjs from the shipped sysop option database.
 *
 * Contains material Copyright (C) 1988-1992 Michael B. Murdock, from Galactic
 * Empire release 3.2e, released by its author under GPL-2.0-or-later. This
 * port is AGPL-3.0-or-later; see NOTICE at the repository root.
 * DO NOT EDIT BY HAND — regenerate, and let
 * test/balance/s00-canon.balance.spec.ts re-check it against the original.
 *
 * GEMAIN.C:909-930 reads S00PLNUM entries of eight options each; GEPLANET.C:
 * 497-527 dispatches each on its type to build a hub, a bare planet, or a
 * wormhole portal.
 *
 * @see reference/ge-upstream/mbmgemp/GE/REL/MBMGEMSG.MSG — the S00P* blocks
 * @see GEMAIN.C:476 S00PLNUM
 * @see GEMAIN.C:909-930 the read loop
 * @see GEPLANET.C:497-528 type dispatch
 */

import { S00Entry } from './galaxy.types';
import { NEUTRAL_ZONE_OWNER } from '../combat/neutral-zone';

/**
 * Number of planets in the neutral-zone fixture.
 * Shipped S00PLNUM, clamped by GEMAIN.C:476 to 3..9.
 */
export const S00_PLNUM = ${plnum} as const;

/**
 * Frozen array of neutral-zone entries for sector (0,0). Index i is plnum i+1.
 *
 * Coordinates are the shipped integer options divided by 10000 (GEMAIN.C:
 * 922-925), giving an offset within the origin sector cell.
 *
 * env and res are QUALITY GRADES, both read through the same four messages —
 * 0 = ${GRADE[0]}, 1 = ${GRADE[1]}, 2 = ${GRADE[2]}, 3 = ${GRADE[3]}
 * (GECMDS.C:2337-2348 prints SCAN12..SCAN15 for env, then again for res;
 * MBMGEMSG.MSG:3570-3585). Higher is better, which GEPLANET.C:280 confirms:
 * production scales with \`(enviorn + resource + 2) * .25\`.
 *
 * The shipped owner is \`*EMPIRE*\` on every entry; this port substitutes
 * NEUTRAL_ZONE_OWNER, a sentinel that cannot collide with a player id.
 * @see src/game/combat/neutral-zone.ts
 */
export const S00: S00Entry[] = Object.freeze([`)

for (const e of entries) {
  lines.push(`  {`)
  lines.push(`    // plnum=${e.plnum} — ${e.name}${BUILD[e.type] ? `, ${BUILD[e.type]}` : ', build_other — bare planet (GEPLANET.C:526)'}`)
  lines.push(`    type: ${e.type},`)
  lines.push(`    name: ${JSON.stringify(e.name)},`)
  lines.push(`    xcoord: ${e.xcoord},`)
  lines.push(`    ycoord: ${e.ycoord},`)
  lines.push(`    env: ${e.env},   // ${GRADE[e.env]}`)
  lines.push(`    res: ${e.res},   // ${GRADE[e.res]}`)
  lines.push(`    owner: NEUTRAL_ZONE_OWNER,`)
  lines.push(`  },`)
}
lines.push(`]) as S00Entry[];`)
console.log(lines.join('\n'))
